# Generated by Django 5.0.4 on 2024-05-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0002_tag_is_verified_alter_tag_name'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='recommendation',
            field=models.ManyToManyField(blank=True, to='Tag.tag'),
        ),
    ]
