# Generated by Django 5.0.4 on 2024-05-16 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0002_tag_is_verified_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='is_verified',
        ),
    ]
