# Generated by Django 5.0.4 on 2024-05-03 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Author', '0002_initial'),
        ('Tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=2048)),
                ('fk_author_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Author.author')),
                ('tags', models.ManyToManyField(to='Tag.tag')),
            ],
        ),
    ]
