# Generated by Django 5.0.4 on 2024-05-04 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comment', '0001_initial'),
        ('Post', '0003_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('comment', models.ManyToManyField(null=True, to='Comment.comment')),
                ('post', models.ManyToManyField(null=True, to='Post.post')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Like.liketype')),
            ],
        ),
    ]
